accounts/urls.py
# accounts/urls.py

from django.urls import path
from .views import login_view, logout_view
from .views import signup_view

app_name = 'accounts'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('signup/', signup_view, name='signup'),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

def redirect_to_recipe_list(request):
    return redirect("/receipts/")

urlpatterns = [
    path("", redirect_to_recipe_list, name="home_page"),
    path('admin/', admin.site.urls),
    path('receipts/', include('receipts.urls')),
    path('accounts/', include('accounts.urls')),
]

receipts/urls.py
from django.urls import path
from .views import receipt_list, category_list, account_list, create_receipt, create_category, create_account

app_name = 'receipts'

urlpatterns = [
    path('', receipt_list, name='home'),
    path('create/', create_receipt, name='create_receipt'),
    path('categories/', category_list, name='category_list'),
    path('accounts/', account_list, name='account_list'),
    path('categories/create/', create_category, name='create_category'),
    path('accounts/create/', create_account, name='create_account'),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(User, related_name='categories', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(User, related_name='accounts', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10, decimal_places=3)
    tax = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateTimeField()
    purchaser = models.ForeignKey(User, related_name='receipts', on_delete=models.CASCADE)
    category = models.ForeignKey(ExpenseCategory, related_name='receipts', on_delete=models.CASCADE, null=True)
    account = models.ForeignKey(Account, related_name='receipts', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f"Receipt #{self.id} - {self.vendor}"

accounts/forms.py
# accounts/forms.py

from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(max_length=150, widget=forms.PasswordInput)

class SignUpForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(max_length=150, widget=forms.PasswordInput)
    password_confirmation = forms.CharField(max_length=150, widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password_confirmation = cleaned_data.get("password_confirmation")

        if password != password_confirmation:
            raise forms.ValidationError("The passwords do not match")

receipts/forms.py
# receipts/forms.py

from django import forms
from .models import Receipt, ExpenseCategory, Account

class ReceiptForm(forms.ModelForm):
    class Meta:
        model = Receipt
        fields = ['vendor', 'total', 'tax', 'date', 'category', 'account']

class ExpenseCategoryForm(forms.ModelForm):
    class Meta:
        model = ExpenseCategory
        fields = ['name']

class AccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['name', 'number']

accounts/views.py
# accounts/views.py

from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .forms import LoginForm
from django.contrib.auth.forms import UserCreationForm
from .forms import SignUpForm
from django.contrib.auth.decorators import login_required
from .models import Account, Receipt

def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('home')
    else:
        form = LoginForm()
    return render(request, 'accounts/login.html', {'form': form})

# accounts/views.py

def logout_view(request):
    logout(request)
    return redirect('accounts:login')


def signup_view(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            User.objects.create_user(username=username, password=password)
            user = authenticate(request, username=username, password=password)
            login(request, user)
            return redirect('receipts:home')
    else:
        form = SignUpForm()
    return render(request, 'accounts/signup.html', {'form': form})

@login_required
def account_list(request):
    accounts = Account.objects.filter(owner=request.user)
    account_data = []
    for account in accounts:
        receipt_count = Receipt.objects.filter(account=account).count()
        account_data.append({'name': account.name, 'number': account.number, 'receipt_count': receipt_count})
    return render(request, 'receipts/account_list.html', {'accounts': account_data})

receipts/views.py
# from django.shortcuts import render
# from .models import Receipt

# def receipt_list(request):
#     receipts = Receipt.objects.all()
#     return render(request, 'receipts/receipt_list.html', {'receipts': receipts})


# receipts/views.py

from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Receipt, ExpenseCategory, ExpenseCategoryForm
from .forms import ReceiptForm, AccountForm


@login_required
def receipt_list(request):
    receipts = Receipt.objects.filter(purchaser=request.user)
    return render(request, 'receipts/receipt_list.html', {'receipts': receipts})


@login_required
def create_receipt(request):
    if request.method == 'POST':
        form = ReceiptForm(request.POST)
        if form.is_valid():
            receipt = form.save(commit=False)
            receipt.purchaser = request.user
            receipt.save()
            return redirect('receipts:home')
    else:
        form = ReceiptForm()
    return render(request, 'receipts/create_receipt.html', {'form': form})

@login_required
def category_list(request):
    categories = ExpenseCategory.objects.filter(owner=request.user)
    category_data = []
    for category in categories:
        receipt_count = Receipt.objects.filter(category=category).count()
        category_data.append({'name': category.name, 'receipt_count': receipt_count})
    return render(request, 'receipts/category_list.html', {'categories': category_data})


@login_required
def create_category(request):
    if request.method == 'POST':
        form = ExpenseCategoryForm(request.POST)
        if form.is_valid():
            category = form.save(commit=False)
            category.owner = request.user
            category.save()
            return redirect('receipts:category_list')
    else:
        form = ExpenseCategoryForm()
    return render(request, 'receipts/create_category.html', {'form': form})

@login_required
def create_account(request):
    if request.method == 'POST':
        form = AccountForm(request.POST)
        if form.is_valid():
            account = form.save(commit=False)
            account.owner = request.user
            account.save()
            return redirect('receipts:account_list')
    else:
        form = AccountForm()
    return render(request, 'receipts/create_account.html', {'form': form})

accounts/templates/accounts/login.html
<!-- accounts/templates/accounts/login.html -->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>

<body>
    <main>
        <div>
            <h1>Login</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Login</button>
            </form>
        </div>
    </main>
</body>

</html>

accounts/templates/accounts/signup.html
<!-- accounts/templates/accounts/signup.html -->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Signup</title>
</head>

<body>
    <main>
        <div>
            <h1>Signup</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Signup</button>
            </form>
        </div>
    </main>
</body>

</html>

expenses/templates/expenses/base.html
<!-- base.html -->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Title Here</title>
</head>

<body>
    <header>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                <li><a href="{% url 'receipts:category_list' %}">Expense Categories</a></li>
                <li><a href="{% url 'receipts:account_list' %}">Accounts</a></li>
                <li><a href="{% url 'receipts:create_category' %}">Create Expense Category</a></li>
                <li><a href="{% url 'receipts:create_account' %}">Create Account</a></li>
                <li><a href="{% url 'receipts:create_receipt' %}">Create Receipt</a></li>
                <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
                <li><a href="{% url 'accounts:login' %}">Login</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>

    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>

</html>

receipts/templates/receipts/create_account.html
<!-- receipts/templates/receipts/create_account.html -->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Account</title>
</head>

<body>
    <main>
        <div>
            <h1>Create Account</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Create</button>
            </form>
        </div>
    </main>
</body>

</html>

receipts/templates/receipts/create_category.html
<!-- receipts/templates/receipts/create_category.html -->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Category</title>
</head>

<body>
    <main>
        <div>
            <h1>Create Category</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Create</button>
            </form>
        </div>
    </main>
</body>

</html>

receipts/templates/receipts/create_receipt.html
<!-- receipts/templates/receipts/create_receipt.html -->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Receipt</title>
</head>

<body>
    <main>
        <div>
            <h1>Create Receipt</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Create</button>
            </form>
        </div>
    </main>
</body>

</html>

receipts/templates/receipts/receipt_list.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Receipts</title>
</head>

<body>
    <main>
        <h1>My Receipts</h1>
        <table>
            <thead>
                <tr>
                    <th>Vendor</th>
                    <th>Total</th>
                    <th>Tax</th>
                    <th>Date</th>
                    <th>Category</th>
                    <th>Account</th>
                </tr>
            </thead>
            <tbody>
                {% for receipt in receipts %}
                <tr>
                    <td>{{ receipt.vendor }}</td>
                    <td>{{ receipt.total }}</td>
                    <td>{{ receipt.tax }}</td>
                    <td>{{ receipt.date|date:"m/d/Y" }}</td>
                    <td>{{ receipt.category.name }}</td>
                    <td>{{ receipt.account.name }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </main>
</body>

</html>